# Tweet Generator Configuration
models:
  planning: anthropic/claude-3-haiku
  creative: anthropic/claude-3-sonnet
  verification: anthropic/claude-3-haiku

engagement:
  optimization_level: high
  hook_variations: 3
  max_hashtags: 2

output:
  auto_post_enabled: false  # Set to true later if you want auto-posting
  dry_run_mode: false
  max_tweets_per_thread: 8

content:
  posts_directory: "_posts"
  notebooks_directory: "_notebooks"
  base_branch: "master"  # Your main branch is master

safety:
  content_filtering: true
  profanity_detection: true
  review_required: true