# Example workflow for fastpages repositories
# Place this file at: .github/workflows/deploy.yml

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for git diff analysis

    - name: convert notebooks and word docs to posts
      uses: ./_action_files
      with:
        BOOL_SAVE_MARKDOWN: true

    - name: Generate tweet threads
      uses: ./.github/actions/tweet-generator
      with:
        openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
        twitter_api_key: ${{ secrets.TWITTER_API_KEY }}
        twitter_api_secret: ${{ secrets.TWITTER_API_SECRET }}
        twitter_access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        posts_directory: "_posts"
        notebooks_directory: "_notebooks"
        dry_run: ${{ github.event_name == 'pull_request' }}
        engagement_level: high
        max_tweets_per_thread: 8
      env:
        AUTO_POST_ENABLED: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push'
      with:
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        publish_dir: ./_site