# Basic configuration for tweet thread generator
# Place this file at: .github/tweet-generator-config.yml

# AI Model Configuration
models:
  planning: google/gemini-2.5-flash-lite      # Fast model for thread planning
  creative: google/gemini-2.5-flash-lite     # High-quality model for content generation
  verification: google/gemini-2.5-flash-lite  # Model for content validation

# Engagement Optimization Settings
engagement:
  optimization_level: high    # Options: low, medium, high
  hook_variations: 3          # Number of hook variations to generate
  max_hashtags: 2            # Maximum hashtags per thread

# Output Configuration
output:
  auto_post_enabled: false    # Enable automatic posting to Twitter
  dry_run_mode: false        # Run without making actual changes
  max_tweets_per_thread: 10  # Maximum tweets per thread

# Directory Configuration
directories:
  posts: "_posts"           # Directory containing blog posts
  notebooks: "_notebooks"   # Directory containing Jupyter notebooks
  generated: ".generated"   # Directory for generated content
  posted: ".posted"        # Directory for posted metadata