name: Generate Tweet Threads

on:
  workflow_dispatch:
    inputs:
      post_slugs:
        description: 'Post slugs to process (comma-separated) or "all" for all eligible posts'
        required: false
        default: 'all'
        type: string
      force_regenerate:
        description: 'Force regenerate even if thread already exists'
        required: false
        default: false
        type: boolean
      dry_run:
        description: 'Run in dry-run mode (no PRs created, no posting)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate-threads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git operations
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/actions/tweet-generator/requirements.txt

      - name: Generate tweet threads
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POST_SLUGS: ${{ github.event.inputs.post_slugs }}
          FORCE_REGENERATE: ${{ github.event.inputs.force_regenerate }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          cd .github/actions/tweet-generator
          python generate_and_commit.py

      - name: Summary
        run: |
          echo "## Tweet Thread Generation Complete" >> $GITHUB_STEP_SUMMARY
          echo "- Post slugs: ${{ github.event.inputs.post_slugs }}" >> $GITHUB_STEP_SUMMARY
          echo "- Force regenerate: ${{ github.event.inputs.force_regenerate }}" >> $GITHUB_STEP_SUMMARY
          echo "- Dry run: ${{ github.event.inputs.dry_run }}" >> $GITHUB_STEP_SUMMARY
          echo "Check the action logs for detailed results." >> $GITHUB_STEP_SUMMARY